# Service jpg_to_png_converter.convert
convert:
  description: "Convert a JPG/WebP image to PNG format from local path, URL, or RTSP stream"
  target: {}
  fields:
    local_input_path:
      description: Path to the local input JPG/WebP file
      example: "/config/www/image.jpg"
      required: false
      selector:
        text: {}

    url_input_path:
      description: URL of the remote JPG/WebP file (direct link)
      example: "https://example.com/image.jpg"
      required: false
      selector:
        text: {}

    rtsp_url:
      description: "RTSP stream URL to capture an image (e.g., from a security camera)"
      example: "rtsp://user:password@192.168.1.100:554/stream1"
      required: false
      selector:
        text: {}

    output_path:
      description: Path where the PNG file should be saved
      example: "/config/www/image.png"
      required: true
      selector:
        text: {}

    resolution:
      description: "Select output resolution"
      example: "original"
      default: "320x240"
      required: false
      selector:
        select:
          options:
            - "original"
            - "320x240"
            - "640x480"
            - "800x600"
            - "1280x720"
            - "1920x1080"

    custom_resolution:
      description: "Custom resolution in WIDTHxHEIGHT format (e.g. 1024x768)"
      example: "1024x768"
      required: false
      selector:
        text:
          placeholder: "WIDTHxHEIGHT"

    optimize_mode:
      name: Optimization Mode
      description: "Choose optimization mode"
      required: false
      default: "none"
      selector:
        select:
          options:
            - label: "None"
              value: "none"
            - label: "ESP32 Mode (256 colors)"
              value: "esp32"
            - label: "Standard Optimization (128 colors)"
              value: "standard"

