# Service jpg_to_png_converter.convert
convert:
  description: "Convert a JPG image to PNG format. Note: 256 colors optimization compresses the image for faster loading on ESP32 devices"
  target: {}
  fields:
    input_path:
      description: Path to the input JPG file
      example: "/config/www/image.jpg"
      required: true
      selector:
        text: {}
    output_path:
      description: Path where the PNG file should be saved
      example: "/config/www/image.png"
      required: false
      selector:
        text: {}
    resolution:
      description: "Select output resolution"
      example: "original"
      default: "320x240"
      required: false
      selector:
        select:
          options:
            - "original"
            - "320x240"
            - "640x480"
            - "800x600"
            - "1280x720"
            - "1920x1080"
    optimize:
      description: "Enable 256 colors optimization (compresses image for faster ESP32 loading)"
      required: false
      default: false
      selector:
        boolean: {}
