convert_jpg_to_png:
  name: Convert JPG to PNG
  description: Convert a JPG image to PNG format
  fields:
    source_path:
      name: Source Path
      description: Path to the source JPG file
      required: true
      selector:
        text:
    destination_path:
      name: Destination Path
      description: Path where the PNG file will be saved
      required: true
      selector:
        text:

